import cv2
import numpy as np
import threading
import time
from flask import Flask, Response
from alignment_calculator import AlignmentCalculator
from docking_gui import DockingGUI
from aruco_helper import get_aruco_detector
from face_model import (build_board, estimate_face_pose, target_in_interface_frame, face_angles_deg)

app = Flask(__name__)

TARGET_DISTANCE = 1.0 

global_frame = None
frame_lock = threading.Lock()

def camera_worker_thread():
    """Reads the local TCP stream generated by rpicam-vid using FFmpeg"""
    global global_frame
    print("[CAMERA] Connecting to local hardware stream on port 8888...")
    
    #Force OpenCV to use FFmpeg to stop the TCP packet tearing
    cap = cv2.VideoCapture("tcp://127.0.0.1:8888?timeout=5000000", cv2.CAP_FFMPEG)
    
    if not cap.isOpened():
        print("[CAMERA] FATAL: Could not connect to stream. Is rpicam-vid running?")
        return

    print("[CAMERA] Connected! Streaming frames to GNC loop...")
    while True:
        ret, frame = cap.read()
        if not ret:
            print("[CAMERA] Frame dropped. Retrying...")
            time.sleep(0.05)
            continue
            
        # SAFETY CHECK: If FFmpeg decoded it as a flat 1-channel image, 
        # convert it to BGR so the GUI can draw colored crosshairs without crashing.
        if len(frame.shape) == 2 or (len(frame.shape) == 3 and frame.shape[2] == 1):
            frame = cv2.cvtColor(frame, cv2.COLOR_GRAY2BGR)
            
        with frame_lock:
            global_frame = frame.copy()

cam_thread = threading.Thread(target=camera_worker_thread, daemon=True)
cam_thread.start()


def get_camera_matrix(frame_width, frame_height):
    focal_length = frame_width * (950.0 / 1280.0)
    center_x = frame_width / 2
    center_y = frame_height / 2
    return np.array([
        [focal_length, 0, center_x],
        [0, focal_length, center_y],
        [0, 0, 1]
    ], dtype=np.float32)

dist_coeffs = np.zeros((5,1), dtype=np.float32)

def generate_telemetry_frames():
    camera_matrix = get_camera_matrix(1280, 800)
    alignment_calc = AlignmentCalculator(TARGET_DISTANCE)
    gui = DockingGUI(1280, 800)
    detector, aruco_dict = get_aruco_detector(cv2.aruco.DICT_4X4_50)
    board = build_board(aruco_dict)

    while True:
        with frame_lock:
            if global_frame is None:
                time.sleep(0.1)
                continue
            frame = global_frame.copy()

        #GNC LOGIC
        corners, ids, rejected = detector.detectMarkers(frame)

        if ids is not None:
            cv2.aruco.drawDetectedMarkers(frame, corners, ids)
            rvec, tvec, n_used = estimate_face_pose(board, corners, ids,
                                                    camera_matrix, dist_coeffs)
            if rvec is not None:
                # one axes triad at the docking-axis center (replaces per-marker axes)
                cv2.drawFrameAxes(frame, camera_matrix, dist_coeffs, rvec, tvec, 0.05)

                pos_cam = tvec.flatten()                    # camera frame  -> DRAWING
                pos_int = target_in_interface_frame(tvec)   # interface frame -> CONTROL
                yaw, pitch, roll = face_angles_deg(rvec)

                error_dict = alignment_calc.calculate_alignment_error(pos_int)
                command_dict = alignment_calc.get_movement_command(error_dict)

                target_point = gui.draw_target_point(frame, pos_cam, camera_matrix)
                gui.draw_alignment_arrows(frame, error_dict, target_point)
                gui.draw_distance_indicator(frame, pos_int, TARGET_DISTANCE, scale_max=1.2)
                gui.draw_status_panel(frame, command_dict, error_dict)
                gui.draw_pose_strip(frame, pos_int[2], yaw, pitch, roll, n_used)
            else:
                gui.draw_status_panel(frame,
                    {'status': 'NO POSE', 'command': 'Markers seen, pose solve failed'}, None)
        else:
            command_dict = {'status': 'NO MARKERS', 'command': 'No markers detected'}
            gui.draw_status_panel(frame, command_dict, None)

        gui.draw_crosshair(frame)

        ret, buffer = cv2.imencode('.jpg', frame)
        frame_bytes = buffer.tobytes()

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')

@app.route('/')
def video_feed():
    return Response(generate_telemetry_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    time.sleep(1)
    print("=" * 50)
    print("TELEMETRY SERVER ONLINE (NUCLEAR FALLBACK ENGINE)")
    print("Port: 5000")
    print("=" * 50)
    app.run(host='0.0.0.0', port=5000, threaded=True)
