import cv2
import numpy as np
import threading
import time
from flask import Flask, Response
from alignment_calculator import AlignmentCalculator
from docking_gui import DockingGUI
from aruco_helper import *

app = Flask(__name__)

MARKER_SIZE = 0.02
TARGET_DISTANCE = 1.0 
REQUIRED_MARKERS = [0, 1, 2, 3]

global_frame = None
frame_lock = threading.Lock()

def camera_worker_thread():
    """Reads the local TCP stream generated by rpicam-vid using FFmpeg"""
    global global_frame
    print("[CAMERA] Connecting to local hardware stream on port 8888...")
    
    #Force OpenCV to use FFmpeg to stop the TCP packet tearing
    cap = cv2.VideoCapture("tcp://127.0.0.1:8888?timeout=5000000", cv2.CAP_FFMPEG)
    
    if not cap.isOpened():
        print("[CAMERA] FATAL: Could not connect to stream. Is rpicam-vid running?")
        return

    print("[CAMERA] Connected! Streaming frames to GNC loop...")
    while True:
        ret, frame = cap.read()
        if not ret:
            print("[CAMERA] Frame dropped. Retrying...")
            time.sleep(0.05)
            continue
            
        # SAFETY CHECK: If FFmpeg decoded it as a flat 1-channel image, 
        # convert it to BGR so the GUI can draw colored crosshairs without crashing.
        if len(frame.shape) == 2 or (len(frame.shape) == 3 and frame.shape[2] == 1):
            frame = cv2.cvtColor(frame, cv2.COLOR_GRAY2BGR)
            
        with frame_lock:
            global_frame = frame.copy()

cam_thread = threading.Thread(target=camera_worker_thread, daemon=True)
cam_thread.start()


def get_camera_matrix(frame_width, frame_height):
    focal_length = frame_width * 0.7
    center_x = frame_width / 2
    center_y = frame_height / 2
    return np.array([
        [focal_length, 0, center_x],
        [0, focal_length, center_y],
        [0, 0, 1]
    ], dtype=np.float32)

dist_coeffs = np.zeros((5,1), dtype=np.float32)

def generate_telemetry_frames():
    camera_matrix = get_camera_matrix(640, 400)
    alignment_calc = AlignmentCalculator(TARGET_DISTANCE, REQUIRED_MARKERS)
    gui = DockingGUI(640, 400)
    detector, aruco_dict = get_aruco_detector(cv2.aruco.DICT_4X4_50)

    while True:
        with frame_lock:
            if global_frame is None:
                time.sleep(0.1)
                continue
            frame = global_frame.copy()

        #GNC LOGIC
        corners, ids, rejected = detector.detectMarkers(frame)

        if ids is not None:
            cv2.aruco.drawDetectedMarkers(frame, corners, ids)
            rvecs, tvecs, _ = estimate_pose_single_markers(
                corners, MARKER_SIZE, camera_matrix, dist_coeffs
            )

            for i in range(len(ids)):
                tvec_corner = tvecs[i].copy()
                R, _ = cv2.Rodrigues(rvecs[i])
                corner_offset = np.array([[-MARKER_SIZE / 2], [-MARKER_SIZE / 2], [0]])
                tvec_corner += R @ corner_offset
                cv2.drawFrameAxes(frame, camera_matrix, dist_coeffs, rvecs[i], tvec_corner, MARKER_SIZE)

            center_position = alignment_calc.calculate_target_center(ids, tvecs)
            error_dict = alignment_calc.calculate_alignment_error(center_position)
            command_dict = alignment_calc.get_movement_command(error_dict)

            if center_position is not None:
                target_point = gui.draw_target_point(frame, center_position, camera_matrix)
                gui.draw_alignment_arrows(frame, error_dict, target_point)
                gui.draw_distance_indicator(frame, center_position, TARGET_DISTANCE)
                gui.draw_status_panel(frame, command_dict, error_dict)
            else:
                detected_ids = set(ids.flatten())
                missing_ids = set(REQUIRED_MARKERS) - detected_ids
                command_dict = {'status': 'INCOMPLETE', 'command': f'Missing: {sorted(missing_ids)}'}
                gui.draw_status_panel(frame, command_dict, None)
        else:
            command_dict = {'status': 'NO MARKERS', 'command': 'No markers detected'}
            gui.draw_status_panel(frame, command_dict, None)

        gui.draw_crosshair(frame)

        ret, buffer = cv2.imencode('.jpg', frame)
        frame_bytes = buffer.tobytes()

        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')

@app.route('/')
def video_feed():
    return Response(generate_telemetry_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    time.sleep(1)
    print("=" * 50)
    print("TELEMETRY SERVER ONLINE (NUCLEAR FALLBACK ENGINE)")
    print("Port: 5000")
    print("=" * 50)
    app.run(host='0.0.0.0', port=5000, threaded=True)
